on:
  push:
    branches:
      - '*'
  pull_request:
  schedule:
    - cron:  '13 5 * * *'

name: Continuous Integration

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.13']
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.0.3
        with:
          go-version: ${{ matrix.go }}
      - name: Setup env for GO
        #  this is only used until the setup-go action is updated
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - name: fmt
        run: go fmt pdc.go
      - name: run
        run: go run pdc.go